version: "3.8"
services:
    app:
        image: php:8.1-fpm
        container_name: mylocations_app
        working_dir: /var/www
        volumes:
            - ./:/var/www:cached
        networks:
            - mylocations_net

    webserver:
        image: nginx:alpine
        container_name: mylocations_webserver
        volumes:
            - ./:/var/www:cached
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "8081:80"
        networks:
            - mylocations_net

    db:
        image: postgres:13
        container_name: mylocations_db
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laraveluser
            POSTGRES_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - mylocations_net

networks:
    mylocations_net:
        driver: bridge

volumes:
    dbdata:
