version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mylocations_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        environment:
            - POSTGRES_DB=places_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=secret
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: mylocations_db
        restart: unless-stopped
        environment:
            - POSTGRES_DB=places_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123
        volumes:
            - pgdata:/var/lib/postgresql/data

    webserver:
        image: nginx:alpine
        container_name: mylocations_webserver
        restart: unless-stopped
        ports:
            - "8082:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

volumes:
    pgdata:
